name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.suffix }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            suffix: linux-amd64
            archive: tar.gz
          - goos: linux
            goarch: arm64
            suffix: linux-arm64
            archive: tar.gz
          - goos: darwin
            goarch: amd64
            suffix: darwin-amd64
            archive: tar.gz
          - goos: darwin
            goarch: arm64
            suffix: darwin-arm64
            archive: tar.gz
          - goos: windows
            goarch: amd64
            suffix: windows-amd64
            archive: zip
            ext: .exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: '0'
        run: |
          go build -ldflags="-s -w" -o kube-browser${{ matrix.ext }} ./cmd/kube-browser/

      - name: Create tar.gz archive
        if: matrix.archive == 'tar.gz'
        run: |
          chmod +x kube-browser
          tar -czf kube-browser-${{ matrix.suffix }}.tar.gz kube-browser
          ls -la kube-browser-${{ matrix.suffix }}.tar.gz

      - name: Create zip archive
        if: matrix.archive == 'zip'
        run: |
          zip kube-browser-${{ matrix.suffix }}.zip kube-browser${{ matrix.ext }}
          ls -la kube-browser-${{ matrix.suffix }}.zip

      - name: Upload artifact (tar.gz)
        if: matrix.archive == 'tar.gz'
        uses: actions/upload-artifact@v4
        with:
          name: kube-browser-${{ matrix.suffix }}
          path: kube-browser-${{ matrix.suffix }}.tar.gz

      - name: Upload artifact (zip)
        if: matrix.archive == 'zip'
        uses: actions/upload-artifact@v4
        with:
          name: kube-browser-${{ matrix.suffix }}
          path: kube-browser-${{ matrix.suffix }}.zip

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: List artifacts
        run: find artifacts -type f

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            artifacts/**/*.tar.gz
            artifacts/**/*.zip
